### ISSUE TITLE
Divisão de tarefas

### ISSUE THREAD

**Issue by expert975** [expert975/controleDeProjetos#1]
Podemos usar esse espaço para discutir como o trabalho será dividido entre o grupo.

**Comment by gabrfern99** [comment]
Test

**Comment by gabrfern99** [comment]
Pois bem, um membro disse que seria interessante caso você disponibilizasse o projeto que você já fez pelo git (upar ele aqui), e ai cada um poderia atualizar/incrementar no próprio git conforme o tempo de cada um

**Comment by expert975** [comment]
Pronto

**Comment by vhaust** [comment]
teste
