### ISSUE TITLE
Métodos

### ISSUE THREAD

**Issue by vdevalerio** [expert975/controleDeProjetos#10]
Quanto à esse modelo, algumas coisas que seriam métodos você colocou como uma classe separada associada à classe que "teria o método". Por que fazer uma nova classe e não apenas o método ?

**Comment by expert975** [comment]
Onde especificamente? Dê exemplos

**Comment by vdevalerio** [comment]
O Projeto deveria ter um método que mudasse a situação dele, algo do tipo: 
 + mudarSituacao ( situacao : Situacao, dataMudanca : Date, agente : Colaborador)

O que mais ou menos o que você fez, só que como uma classe associada

**Comment by expert975** [comment]
Sim, o modelo precisa mesmo desse método. A intenção em associar Projeto com AlteracaoAndamento é manter uma história de todas as mudanças

**Comment by vdevalerio** [comment]
Entendi, obrigado.
