### ISSUE TITLE
Complete o diagrama UML

### ISSUE THREAD

**Issue by expert975** [expert975/controleDeProjetos#15]
Faltam métodos em nosso diagrama UML. Analise e escreva-os.

**Comment by vdevalerio** [comment]
Oi, tentei fazer um commit, mas quando dei o push deu esses erros :
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/expert975/controleDeProjetos.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/expert975/controleDeProjetos.git'
Como eu faço pra enviar minhas alterações ?

**Comment by vdevalerio** [comment]
Ah, eu tive que criar um new branch, deu certo agr ahsuahsuahs

**Comment by gabrfern99** [comment]
Sexta-feira reunimos na aula e gastamos as duas horas para finalizar os métodos, já que teremos 4 membros, enquanto isso fazemos o possível

**Comment by vdevalerio** [comment]
Eu havia feito a modificação em algumas variáveis pois, por convenção, quando há variáveis com mesmo nome, costuma-se adicionar sufixos pra diferenciação entre eles. Mas uma vez que você os considera desnecessários, refiz o commit mantendo o nome das variáveis.

**Comment by expert975** [comment]
- Use `git pull` `git checkout master` `git log` para ver os commits feitos na branch master.
> eu não sei se o commit foi pra master também.

> ! [remote rejected] master -> master (protected branch hook declined)
-  Podemos mandar comentários sobre os commits de um pull request no pull request para mantermos as conversas em tópicos: #16.
- As variáveis têm o mesmo nome, mas estão em escopos diferentes. É até melhor tê-las com o mesmo nome, pois assim não é necessário se preocupar com pequenas variações e olhar qual é seu nome exato; sabe-se que é `nome`.
```java
Colaborador colaborador = new Colaborador();
String nomeColaborador = colaborador.getNome();

Departamento departamento = new Departamento();
String nomeDepartamento = departamento.getNome();
```
