### ISSUE TITLE
Pesquisa sobre a API dos Correios

### ISSUE THREAD

**Issue by expert975** [expert975/controleDeProjetos#25]
Precisamos implentar pesquisa de endereços usando a API dos Correios

**Comment by gabrfern99** [comment]
https://pt.stackoverflow.com/questions/400/como-buscar-um-endere%C3%A7o-por-cep-nos-correios
https://postmon.com.br/
Encontrei essa API de fácil utilização e que utiliza database dos correios

**Comment by gabrfern99** [comment]
Porém busca somente pelo CEP (que trás o restante do endereço)

**Comment by vhaust** [comment]
Eu fiz uma classe cliente do Correios WebService

**Comment by vdevalerio** [comment]
Eu perguntei para o Gilmar sobre essa API e ele respondeu da seguinte maneira:
"Não precisa de você implementar a comunicação com o web service dos correios. Isto está fora do escopo do trabalho de vocês, pois não foi ensinado isto na nossa disciplina.

O que vocês precisam fazer é:

1 - Criar uma interface chamada correios. Esta interface deverá disponibilizar os métodos para qualquer tipo de consulta a endereço que vocês precisarem. E todos estes métodos devem retornar um objeto do tipo endereco.
2 - Toda vez que for instanciar um endereco ele deve ser instanciado como uma solicitação a esta interface. Exemplo:

Endereco end = Correios.consultaPorCep("74393200");

Só isto é suficiente para o projeto.

Um abraço."

Iremos implementar a API ou só fazer as interfaces mesmo ?

**Comment by vhaust** [comment]
Os dois são possíveis e atualmente funcionais

**Comment by expert975** [comment]
4c47ddd1639874a845ab247fe10ce2d7a963594e
