### ISSUE TITLE
Criação do diagrama UML

### ISSUE THREAD

**Issue by expert975** [expert975/controleDeProjetos#8]
Por favor criem issues demandando a criação de diagramas de classe. Criando 1 issue por classe podemos especificar quem está fazendo o quê, assim evitando trabalho duplicado.

**Comment by vdevalerio** [comment]
No momento estou fazendo a classe "Projeto", e tentarei fazer a classe "Departamento" esta noite ainda.

**Comment by expert975** [comment]
@vdevalerio seu trabalho está avançado? Também estou fazendo essas classes

**Comment by vdevalerio** [comment]
nem tanto na verdade e.e', comecei agora

**Comment by expert975** [comment]
Então vou mandar minha versão e tu modifica ela. Pode ser?

**Comment by vdevalerio** [comment]
Ok

**Comment by expert975** [comment]
Imagino que todas as classes que precisaremos estão no lugar. Por favor verifique o diagrama e sugira correções.
